### PR TITLE
Update to MC 1.9, forge 12.16.0.1863-1.9

### PR DESCRIPTION
**Pull request by Awkanic**
- Applied the migration map from Kashike and bonii-xx.
- Updated the other functions to their 1.9 counterparts.
- Downgraded the gradle wrapper to the same version as forge (2.7).
- Updated JEIPlugin based on the examples in the updated JEIPlugin repo.

### CODE REVIEW

**Comment by gr8pefish** [comment]
I just made a new branch for 1.9, do a PR into that please (it's the default branch now, so it should be easy) and I will accept it.

**Comment by gr8pefish** [comment]
I changed my mind, might as well just update to 1.9 by default. PR accepted, thank you!

**Comment by Awkanic** [comment]
Thanks for the original mod. We've missed it and Iron Backpacks since we updated.

**Comment by gr8pefish** [comment]
Thank you! It means a lot :)

I've been super busy with school recently, hence my lack of progress lately. However, in a month the semester is over and I can resume modding, so you can hopefully expect a full Iron Backpacks port sometime after that. I might try and do a quick and dirty port first, we will see.

**Pull request merged**
